# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/den.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeepFakeDetection(object):
    def setupUi(self, DeepFakeDetection):
        DeepFakeDetection.setObjectName("DeepFakeDetection")
        DeepFakeDetection.resize(916, 828)
        DeepFakeDetection.setMinimumSize(QtCore.QSize(916, 828))
        DeepFakeDetection.setMaximumSize(QtCore.QSize(916, 848))
        DeepFakeDetection.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        DeepFakeDetection.setFocusPolicy(QtCore.Qt.StrongFocus)
        DeepFakeDetection.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(DeepFakeDetection)
        self.centralwidget.setObjectName("centralwidget")
        self.widgetAll = QtWidgets.QWidget(self.centralwidget)
        self.widgetAll.setGeometry(QtCore.QRect(0, 0, 911, 791))
        self.widgetAll.setStyleSheet("background-color: rgb(51, 59, 71);\n"
"")
        self.widgetAll.setObjectName("widgetAll")
        self.widgetVideo = QtWidgets.QWidget(self.widgetAll)
        self.widgetVideo.setGeometry(QtCore.QRect(10, 10, 881, 461))
        self.widgetVideo.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"")
        self.widgetVideo.setObjectName("widgetVideo")
        self.scrollArea = QtWidgets.QScrollArea(self.widgetAll)
        self.scrollArea.setGeometry(QtCore.QRect(20, 640, 231, 71))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.check_box_vision_transformer = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.check_box_vision_transformer.setGeometry(QtCore.QRect(10, 10, 211, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.check_box_vision_transformer.setFont(font)
        self.check_box_vision_transformer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_box_vision_transformer.setStyleSheet("color: rgb(255, 255, 255);")
        self.check_box_vision_transformer.setObjectName("check_box_vision_transformer")
        self.check_box_cnn = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.check_box_cnn.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.check_box_cnn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_box_cnn.setStyleSheet("color: rgb(255, 255, 255);")
        self.check_box_cnn.setObjectName("check_box_cnn")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.labelResult = QtWidgets.QLabel(self.widgetAll)
        self.labelResult.setGeometry(QtCore.QRect(440, 600, 121, 41))
        self.labelResult.setStyleSheet("color:rgb(255, 255, 255)")
        self.labelResult.setObjectName("labelResult")
        self.progressBarVisionTransformer = QtWidgets.QProgressBar(self.widgetAll)
        self.progressBarVisionTransformer.setGeometry(QtCore.QRect(430, 720, 118, 23))
        self.progressBarVisionTransformer.setStyleSheet("color: rgb(255, 255, 255);")
        self.progressBarVisionTransformer.setProperty("value", 0)
        self.progressBarVisionTransformer.setObjectName("progressBarVisionTransformer")
        self.label_Resimler = QtWidgets.QLabel(self.widgetAll)
        self.label_Resimler.setGeometry(QtCore.QRect(650, 490, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Resimler.setFont(font)
        self.label_Resimler.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Resimler.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Resimler.setObjectName("label_Resimler")
        self.comboBoxResimler = QtWidgets.QComboBox(self.widgetAll)
        self.comboBoxResimler.setGeometry(QtCore.QRect(680, 530, 171, 20))
        self.comboBoxResimler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBoxResimler.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.comboBoxResimler.setObjectName("comboBoxResimler")
        self.pushButtonInference = QtWidgets.QPushButton(self.widgetAll)
        self.pushButtonInference.setGeometry(QtCore.QRect(430, 510, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonInference.setFont(font)
        self.pushButtonInference.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonInference.setStyleSheet("QPushButton#pushButtonInference{\n"
"    background-color: qlineargradient(spread:pad, x:1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton#pushButtonInference:hover{\n"
"    background-color: qlineargradient(spread:pad, x:1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#pushButtonInference:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105,118,132,200);\n"
"}\n"
"border: 1px solid black;\n"
"border-radius:5px;")
        self.pushButtonInference.setObjectName("pushButtonInference")
        self.widgetButtons = QtWidgets.QWidget(self.widgetAll)
        self.widgetButtons.setGeometry(QtCore.QRect(30, 490, 321, 61))
        self.widgetButtons.setStyleSheet("QPushButton#pushButtonOynat{\n"
"    background-color: qlineargradient(spread:pad, x:1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton#pushButtonOynat:hover{\n"
"    background-color: qlineargradient(spread:pad, x:1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#pushButtonOynat:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105,118,132,200);\n"
"}\n"
"QPushButton#pushButtonDurdur{\n"
"    background-color: qlineargradient(spread:pad, x:1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton#pushButtonDurdur:hover{\n"
"    background-color: qlineargradient(spread:pad, x:1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#pushButtonDurdur:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105,118,132,200);\n"
"}\n"
"QPushButton#pushButtonDuraklat{\n"
"    background-color: qlineargradient(spread:pad, x:1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton#pushButtonDuraklat:hover{\n"
"    background-color: qlineargradient(spread:pad, x:1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#pushButtonDuraklat:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105,118,132,200);\n"
"}\n"
"\n"
"")
        self.widgetButtons.setObjectName("widgetButtons")
        self.pushButtonOynat = QtWidgets.QPushButton(self.widgetButtons)
        self.pushButtonOynat.setGeometry(QtCore.QRect(20, 10, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOynat.setFont(font)
        self.pushButtonOynat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonOynat.setObjectName("pushButtonOynat")
        self.pushButtonDuraklat = QtWidgets.QPushButton(self.widgetButtons)
        self.pushButtonDuraklat.setGeometry(QtCore.QRect(120, 10, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDuraklat.setFont(font)
        self.pushButtonDuraklat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonDuraklat.setObjectName("pushButtonDuraklat")
        self.pushButtonDurdur = QtWidgets.QPushButton(self.widgetButtons)
        self.pushButtonDurdur.setGeometry(QtCore.QRect(220, 10, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDurdur.setFont(font)
        self.pushButtonDurdur.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonDurdur.setObjectName("pushButtonDurdur")
        DeepFakeDetection.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DeepFakeDetection)
        self.statusbar.setObjectName("statusbar")
        DeepFakeDetection.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(DeepFakeDetection)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 21))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        DeepFakeDetection.setMenuBar(self.menubar)
        self.actionAc = QtWidgets.QAction(DeepFakeDetection)
        self.actionAc.setObjectName("actionAc")
        self.actionKapat = QtWidgets.QAction(DeepFakeDetection)
        self.actionKapat.setObjectName("actionKapat")
        self.menuDosya.addAction(self.actionAc)
        self.menuDosya.addAction(self.actionKapat)
        self.menubar.addAction(self.menuDosya.menuAction())

        self.retranslateUi(DeepFakeDetection)
        QtCore.QMetaObject.connectSlotsByName(DeepFakeDetection)

    def retranslateUi(self, DeepFakeDetection):
        _translate = QtCore.QCoreApplication.translate
        DeepFakeDetection.setWindowTitle(_translate("DeepFakeDetection", "Deep Fake Detection"))
        self.check_box_vision_transformer.setText(_translate("DeepFakeDetection", "EfficientNet and Vision Transformers"))
        self.check_box_cnn.setText(_translate("DeepFakeDetection", "CNN"))
        self.labelResult.setText(_translate("DeepFakeDetection", "2"))
        self.label_Resimler.setText(_translate("DeepFakeDetection", "Çıkarılan Resimler"))
        self.pushButtonInference.setText(_translate("DeepFakeDetection", "Çıkarım"))
        self.pushButtonOynat.setText(_translate("DeepFakeDetection", "OYNAT"))
        self.pushButtonDuraklat.setText(_translate("DeepFakeDetection", "DURAKLAT"))
        self.pushButtonDurdur.setText(_translate("DeepFakeDetection", "DURDUR"))
        self.menuDosya.setTitle(_translate("DeepFakeDetection", "Dosya"))
        self.actionAc.setText(_translate("DeepFakeDetection", "Aç"))
        self.actionKapat.setText(_translate("DeepFakeDetection", "Kapat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeepFakeDetection = QtWidgets.QMainWindow()
    ui = Ui_DeepFakeDetection()
    ui.setupUi(DeepFakeDetection)
    DeepFakeDetection.show()
    sys.exit(app.exec_())
