# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Userregister.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserRegister(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(464, 371)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label_KAdi = QtWidgets.QLabel(Dialog)
        self.label_KAdi.setGeometry(QtCore.QRect(90, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_KAdi.setFont(font)
        self.label_KAdi.setObjectName("label_KAdi")
        self.label_Sifre = QtWidgets.QLabel(Dialog)
        self.label_Sifre.setGeometry(QtCore.QRect(90, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Sifre.setFont(font)
        self.label_Sifre.setObjectName("label_Sifre")
        self.push_button_kayit_ol = QtWidgets.QPushButton(Dialog)
        self.push_button_kayit_ol.setGeometry(QtCore.QRect(250, 310, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.push_button_kayit_ol.setFont(font)
        self.push_button_kayit_ol.setObjectName("push_button_kayit_ol")
        self.label_Mail = QtWidgets.QLabel(Dialog)
        self.label_Mail.setGeometry(QtCore.QRect(90, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Mail.setFont(font)
        self.label_Mail.setObjectName("label_Mail")
        self.line_edit_username = QtWidgets.QLineEdit(Dialog)
        self.line_edit_username.setGeometry(QtCore.QRect(250, 80, 113, 20))
        self.line_edit_username.setObjectName("line_edit_username")
        self.line_edit_password = QtWidgets.QLineEdit(Dialog)
        self.line_edit_password.setGeometry(QtCore.QRect(240, 130, 113, 20))
        self.line_edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password.setObjectName("line_edit_password")
        self.line_edit_mail = QtWidgets.QLineEdit(Dialog)
        self.line_edit_mail.setGeometry(QtCore.QRect(240, 170, 113, 20))
        self.line_edit_mail.setObjectName("line_edit_mail")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_KAdi.setText(_translate("Dialog", "Kullanıcı Adı :"))
        self.label_Sifre.setText(_translate("Dialog", "Şifre              :"))
        self.push_button_kayit_ol.setText(_translate("Dialog", "Kayıt Ol"))
        self.label_Mail.setText(_translate("Dialog", "Mail               :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
